services:
  - type: web
    name: eaxy-backend
    runtime: docker
    region: frankfurt
    dockerfilePath: Dockerfile
    healthCheckPath: /api/health
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: eaxy-db
          property: connectionString
      - key: SECRET_KEY
        value: eaxy2025secret

databases:
  - name: eaxy-db
    region: frankfurt
