services:
  - type: web
    name: eaxy-backend
    runtime: docker
    plan: free
    dockerfilePath: Dockerfile
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: eaxy-db
          property: connectionString
      - key: SECRET_KEY
        value: eaxy2025secret

databases:
  - name: eaxy-db
    plan: free
    region: Frankfurt
    databaseName: eaxy_db
    user: eaxy_user
