services:
  - type: web
    name: eaxy-backend
    env: docker
    plan: free
    dockerfilePath: Dockerfile
    envVars:
      - key: DATABASE_URL
        value: ${DATABASE_URL}
      - key: SECRET_KEY
        value: ${SECRET_KEY}
  - type: postgres
    name: eaxy-db
    plan: free
    envVars:
      - key: DATABASE_URL
        value: postgresql://postgres:postgres@internal-db:5432/eaxy_db
